# Generated by Django 4.1 on 2022-12-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_alter_img_filetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examheader',
            name='duration_m',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
