# Generated by Django 4.1 on 2023-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0005_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Pages',
                'managed': True,
            },
        ),
    ]
